CREATE TABLE VALIDATION_RESULTS_SUMMARY (
  ID NUMBER(38, 0) NOT NULL PRIMARY KEY,
  VALIDATION_RULE_ID NUMBER(38,0) NOT NULL,
  DATASET_ID NUMBER(38,0) NOT NULL,
  TOTAL_RECORDS_RUN NUMBER(38,0) NOT NULL,
  NUMBER_OF_FAILURES NUMBER(38,0) NOT NULL,
  STATUS VARCHAR2(50),
  ERROR_MESSAGE VARCHAR2(2500),
  CONSTRAINT SUMMARY_RULE_FK FOREIGN KEY (VALIDATION_RULE_ID) REFERENCES VALIDATION_RULE (ID),
    CONSTRAINT SUMMARY_DATASET_FK FOREIGN KEY (DATASET_ID) REFERENCES DATASET (ID)
);
