ALTER TABLE VALIDATION_RULE ADD DATASET_SCHEMA_ID NUMBER(19, 0);

ALTER TABLE VALIDATION_RULE
  ADD CONSTRAINT RULE_DATASET_SCHEMA_FK FOREIGN KEY (DATASET_SCHEMA_ID) REFERENCES DATASET_SCHEMA (ID);

UPDATE VALIDATION_RULE r1
SET DATASET_SCHEMA_ID = (
  SELECT ds.ID FROM DATASET_SCHEMA ds
    INNER JOIN VALIDATION_RULE_SET rs ON ds.VALIDATION_RULE_SET_ID = rs.ID
    INNER JOIN VALIDATION_RULE r2 ON rs.ID = r2.VALIDATION_RULE_SET_ID
  WHERE r1.ID = r2.ID
);

ALTER TABLE VALIDATION_RULE
  MODIFY DATASET_SCHEMA_ID NOT NULL;

ALTER TABLE VALIDATION_RULE
  DROP CONSTRAINT UNIQUE_RULE;

ALTER TABLE VALIDATION_RULE
  ADD CONSTRAINT UNIQUE_RULE UNIQUE (DATASET_SCHEMA_ID, RULE_ID, VERSION, START_DATE, END_DATE);

ALTER TABLE VALIDATION_RULE
  DROP COLUMN VALIDATION_RULE_SET_ID;

ALTER TABLE DATASET_SCHEMA DROP COLUMN VALIDATION_RULE_SET_ID;

DROP TABLE VALIDATION_RULE_SET;