CREATE TABLE VALIDATION_RULE_SCHEMA_FIELD (
  VALIDATION_RULE_ID NUMBER(38, 0) NOT NULL,
  SCHEMA_FIELD_ID    NUMBER(38, 0) NOT NULL,
  CONSTRAINT VALIDATION_RULE_FK FOREIGN KEY (VALIDATION_RULE_ID) REFERENCES VALIDATION_RULE (ID),
  CONSTRAINT FIELD_FK FOREIGN KEY (SCHEMA_FIELD_ID) REFERENCES DATASET_SCHEMA_FIELD (ID),
  CONSTRAINT V_RULE_S_FIELD_PK PRIMARY KEY (VALIDATION_RULE_ID, SCHEMA_FIELD_ID)
);