ALTER TABLE DATASET_SCHEMA
  ADD START_DATE DATE;

UPDATE DATASET_SCHEMA
SET START_DATE = (DATE '1970-01-01');

ALTER TABLE DATASET_SCHEMA
  MODIFY START_DATE DATE NOT NULL;

ALTER TABLE DATASET_SCHEMA
  ADD END_DATE DATE;