ALTER TABLE DATASET ADD ENTITY_CODE varchar(255);
ALTER TABLE DATASET ADD REFERENCE_DATE DATE;
ALTER TABLE DATASET
  MODIFY METADATA_KEY NULL;

ALTER TABLE STAGING_DATA_SET ADD ENTITY_CODE varchar(255);
ALTER TABLE STAGING_DATA_SET  ADD REFERENCE_DATE DATE;
ALTER TABLE STAGING_DATA_SET
  MODIFY METADATA_KEY NULL;

