ALTER TABLE PRODUCT_CONFIG
  DROP CONSTRAINT PRODUCT_CONFIG_NAME_UNIQUE;

ALTER TABLE PRODUCT_CONFIG
  ADD CONSTRAINT PRODUCT_CONFIG_UNIQUE UNIQUE (NAME, VERSION);

ALTER TABLE PRODUCT_CONFIG
  ADD CREATED_TIME TIMESTAMP;

UPDATE PRODUCT_CONFIG
SET CREATED_TIME = (TIMESTAMP '2018-10-01 00:00:00');

ALTER TABLE PRODUCT_CONFIG
  MODIFY CREATED_TIME TIMESTAMP NOT NULL;

ALTER TABLE PRODUCT_CONFIG
  ADD IMPORT_REQUEST_ID NUMBER(38, 0);