ALTER TABLE PIPELINE_STEP_INVC_DATASET ADD DATASET_RUN_KEY NUMBER(19,0) DEFAULT NULL;

-- UPDATE PIPELINE_STEP_INVC_DATASET PSID
-- SET DATASET_RUN_KEY = (
--     SELECT D.RUN_KEY AS DATASET_RUN_KEY
--     FROM DATASET D
--     WHERE PSID.DATASET_ID = D.ID
-- )
-- WHERE PSID.DATASET_ID IS NOT NULL;