ALTER TABLE DATASET ADD ROW_KEY_SEED NUMBER(19,0) DEFAULT NULL;
ALTER TABLE DATASET ADD RUN_KEY NUMBER(19,0) DEFAULT 1;
ALTER TABLE DATASET ADD LAST_UPDATED TIMESTAMP;

UPDATE DATASET SET
ROW_KEY_SEED = CASE WHEN PIPELINE_JOB_ID IS NOT NULL THEN PIPELINE_JOB_ID ELSE STAGING_JOB_ID END,
RUN_KEY = ID,
LAST_UPDATED = CREATED_TIME
;

ALTER TABLE DATASET ADD CONSTRAINT UNIQUE_DATASET_RUN UNIQUE (NAME, ENTITY_CODE, REFERENCE_DATE, RUN_KEY);

ALTER TABLE STAGING_DATA_SET ADD DATASET_ID NUMBER(19,0) DEFAULT NULL;

UPDATE STAGING_DATA_SET SDS1 SET
DATASET_ID = (
    SELECT D.ID AS DATASET_ID
    FROM DATASET D
    INNER JOIN STAGING_DATA_SET SDS2
        ON D.STAGING_JOB_ID = SDS2.SERVICE_REQUEST_ID AND D.NAME = SDS2.DATASET
    WHERE SDS1.ID = SDS2.ID
);
