ALTER TABLE SVC_SERVICE_REQUEST ADD START_TIME TIMESTAMP;
ALTER TABLE SVC_SERVICE_REQUEST ADD END_TIME TIMESTAMP;
ALTER TABLE SVC_SERVICE_REQUEST ADD STATUS VARCHAR(10);
ALTER TABLE SVC_SERVICE_REQUEST ADD EXIT_CODE VARCHAR(10);

UPDATE SVC_SERVICE_REQUEST SR
SET (START_TIME, END_TIME, STATUS, EXIT_CODE) = (
    SELECT START_TIME, END_TIME, STATUS, EXIT_CODE
    FROM BATCH_JOB_EXECUTION BJE
    WHERE SR.JOB_EXECUTION_ID IS NOT NULL AND SR.JOB_EXECUTION_ID = BJE.JOB_EXECUTION_ID
);
