CREATE TABLE CAL_HOLIDAY (
  ID NUMBER(38, 0) NOT NULL PRIMARY KEY,
  PRODUCT_NAME VARCHAR(255) NOT NULL,
  HOLIDAY_DATE DATE NOT NULL,
  NAME VARCHAR(255),
  CONSTRAINT "Unique Holiday" UNIQUE (PRODUCT_NAME, HOLIDAY_DATE)
);
