#!/usr/bin/env bash

databaseEngine="^(oracle|mssqlserver|mysql)$"
credentialsNote="\t Note: DBA credentials must be setup in ~/.m2/settings.xml\n\t in order to generate a unique schema and run the migrations against it."

if [[ $# -gt 0 && $1 =~ $databaseEngine ]]; then
    echo "Running Flyway migrations for [$1] database"
    echo -e ${credentialsNote}
    echo
    echo
    mvn -fn -f ignis-server/pom.xml -P jenkins antrun:run@echo-schema-name \
                                               sql:execute@create-$1-database \
                                               flyway:migrate@migrate-$1-database \
                                               sql:execute@drop-$1-database  2>&1 | tee -a target/migrations.log
    echo
    echo -e "\t Note: manually remove a schema/database:\n\t mvn -f ignis-server/pom.xml -P jenkins sql:execute@drop-$1-database -Ddatabase.schema.name=\${dbName}"
else
	echo "params not recognised"
	echo "  1st param needs to be one of: "${databaseEngine:2:-2}
	echo -e ${credentialsNote}
fi