// Remove Schema With ID
DELETE {{context-path}}/api/internal/tables/-10
Authorization: Basic {{user-pass}}

###


// Create FRY14QCIL Schema
POST {{context-path}}/api/internal/tables/file
Authorization: Basic {{user-pass}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="DEWHL001.json"
Content-Type: application/json

< ./../../ignis-functional-test/src/main/resources/requests/staging/DEWHL001/FRY14Q_CIL-DEWHL001.schema_and_rules.json

--WebAppBoundary--

###

// Create Field on schema
POST {{context-path}}/api/v1/productConfigs/10000/schemas/10021/fields
Authorization: Basic {{user-pass}}
Content-Type: application/json

{
  "name": "B3",
  "type": "int"
}

###
