DECLARE @ConstraintName varchar(200)
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID('SVC_SERVICE_REQUEST')
AND PARENT_COLUMN_ID = (
    SELECT column_id FROM sys.columns
    WHERE NAME = N'MESSAGE_ID'
    AND object_id = OBJECT_ID(N'SVC_SERVICE_REQUEST')
    )
IF @ConstraintName IS NOT NULL
    EXEC('ALTER TABLE SVC_SERVICE_REQUEST DROP CONSTRAINT ' + @ConstraintName);
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN MESSAGE_ID;

GO

DECLARE @ConstraintName varchar(200)
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID('SVC_SERVICE_REQUEST')
AND PARENT_COLUMN_ID = (
    SELECT column_id FROM sys.columns
    WHERE NAME = N'SENDER_SYSTEM_ID'
    AND object_id = OBJECT_ID(N'SVC_SERVICE_REQUEST')
    )
IF @ConstraintName IS NOT NULL
    EXEC('ALTER TABLE SVC_SERVICE_REQUEST DROP CONSTRAINT ' + @ConstraintName);
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN SENDER_SYSTEM_ID;

GO

DECLARE @ConstraintName varchar(200)
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID('SVC_SERVICE_REQUEST')
AND PARENT_COLUMN_ID = (
    SELECT column_id FROM sys.columns
    WHERE NAME = N'RECEIVER_SERVICE_NAME'
    AND object_id = OBJECT_ID(N'SVC_SERVICE_REQUEST')
    )
IF @ConstraintName IS NOT NULL
    EXEC('ALTER TABLE SVC_SERVICE_REQUEST DROP CONSTRAINT ' + @ConstraintName);
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN RECEIVER_SERVICE_NAME;

GO

DECLARE @ConstraintName varchar(200)
SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
WHERE PARENT_OBJECT_ID = OBJECT_ID('SVC_SERVICE_REQUEST')
AND PARENT_COLUMN_ID = (
    SELECT column_id FROM sys.columns
    WHERE NAME = N'CORRELATION_ID'
    AND object_id = OBJECT_ID(N'SVC_SERVICE_REQUEST')
    )
IF @ConstraintName IS NOT NULL
    EXEC('ALTER TABLE SVC_SERVICE_REQUEST DROP CONSTRAINT ' + @ConstraintName);
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN CORRELATION_ID;

GO

ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN IS_DELETED;

ALTER TABLE DATASET ALTER COLUMN NAME varchar(100);
ALTER TABLE DATASET ALTER COLUMN TABLE_NAME varchar(100);

ALTER TABLE STAGING_DATA_SET ALTER COLUMN DATASET varchar(100);
ALTER TABLE STAGING_DATA_SET ALTER COLUMN TABLE_NAME varchar(100);
