CREATE TABLE VALIDATION_RULE_SET (
  ID BIGINT NOT NULL PRIMARY KEY,
  NAME        varchar(100) NOT NULL,
  DATASET_NAME varchar(255) NOT NULL
);

CREATE TABLE VALIDATION_RULE (
  ID BIGINT NOT NULL PRIMARY KEY,
  VALIDATION_RULE_SET_ID BIGINT NOT NULL,
  REGULATOR_ID varchar(100),
  RULE_TYPE varchar(50),
  SEVERITY varchar(50),
  VERSION INT,
  START_DATE datetime2 DEFAULT NULL,
  END_DATE datetime2 DEFAULT NULL,
  NAME varchar(100),
  DESCRIPTION varchar(2000),
  EXPRESSION varchar(1000),
    CONSTRAINT RULE_RULE_SET_FK FOREIGN KEY (VALIDATION_RULE_SET_ID) REFERENCES VALIDATION_RULE_SET (ID)

);
