CREATE TABLE VALIDATION_RESULTS_SUMMARY (
  ID BIGINT NOT NULL PRIMARY KEY,
  VALIDATION_RULE_ID BIGINT NOT NULL,
  DATASET_ID BIGINT NOT NULL,
  TOTAL_RECORDS_RUN BIGINT NOT NULL,
  NUMBER_OF_FAILURES BIGINT NOT NULL,
  STATUS VARCHAR(50),
  ERROR_MESSAGE VARCHAR(2500),
    CONSTRAINT SUMMARY_RULE_FK FOREIGN KEY (VALIDATION_RULE_ID) REFERENCES VALIDATION_RULE (ID),
    CONSTRAINT SUMMARY_DATASET_FK FOREIGN KEY (DATASET_ID) REFERENCES DATASET (ID)
);
