ALTER TABLE DATASET ADD ENTITY_CODE varchar(255) DEFAULT NULL NULL;
ALTER TABLE DATASET ADD REFERENCE_DATE DATE;

ALTER TABLE DATASET ALTER COLUMN METADATA_KEY varchar(64);

ALTER TABLE STAGING_DATA_SET ADD ENTITY_CODE varchar(255);
ALTER TABLE STAGING_DATA_SET ADD REFERENCE_DATE DATE;

ALTER TABLE STAGING_DATA_SET ALTER COLUMN METADATA_KEY VARCHAR(64);
