ALTER TABLE DATASET_SCHEMA
  ADD START_DATE DATE;

GO

UPDATE DATASET_SCHEMA
SET START_DATE = '1970-01-01';

ALTER TABLE DATASET_SCHEMA ALTER COLUMN START_DATE DATE NOT NULL;

ALTER TABLE DATASET_SCHEMA
  ADD END_DATE DATE;