ALTER TABLE DATASET_SCHEMA
  ADD PRODUCT_ID BIGINT;

GO

UPDATE DATASET_SCHEMA
SET PRODUCT_ID = P.ID
    FROM DATASET_SCHEMA DS2
    join PRODUCT_CONFIG_DATASET_SCHEMA PDS on DS2.ID = PDS.DATASET_SCHEMA_ID
    join PRODUCT_CONFIG P on P.ID = PDS.PRODUCT_CONFIG_ID;

ALTER TABLE DATASET_SCHEMA ADD CONSTRAINT DS_PRODUCT_FK
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_CONFIG (ID);