ALTER TABLE PIPELINE ADD PRODUCT_ID BIGINT;

ALTER TABLE PIPELINE ADD CONSTRAINT PIPELINE_PRODUCT_FK
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_CONFIG (ID);

ALTER TABLE DATASET ADD PIPELINE_JOB_ID BIGINT;
ALTER TABLE DATASET ADD PIPELINE_INVOCATION_ID BIGINT;


CREATE TABLE PIPELINE_INVOCATION (
  ID BIGINT NOT NULL,
  ENTITY_CODE VARCHAR(255) DEFAULT NULL,
  REFERENCE_DATE DATE NOT NULL,
  PIPELINE_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PIP_INVC_FK FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE (ID)
);

CREATE TABLE PIPELINE_STEP_INVOCATION (
  ID BIGINT NOT NULL,
  PIPELINE_INVOCATION_ID BIGINT NOT NULL,
  PIPELINE_STEP_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PIP_S_PIP_INVC_FK FOREIGN KEY (PIPELINE_INVOCATION_ID) REFERENCES PIPELINE_INVOCATION (ID),
  CONSTRAINT PIP_INVC_PIP_STEP_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP (ID)
);