ALTER TABLE PIPELINE_STEP_SELECT
    ADD ID BIGINT, OUTPUT_FIELD_ID BIGINT, IS_WINDOW BIT DEFAULT 0;
GO

UPDATE PIPELINE_STEP_SELECT SET ID = NEXT VALUE FOR HIBERNATE_SEQUENCE;

ALTER TABLE PIPELINE_STEP_SELECT ALTER COLUMN ID BIGINT NOT NULL;

ALTER TABLE PIPELINE_STEP_SELECT DROP CONSTRAINT UNIQUE_VALUE;

ALTER TABLE PIPELINE_STEP_SELECT
    ADD CONSTRAINT PIP_STEP_SELECT_PK PRIMARY KEY (ID),
    CONSTRAINT PIP_STEP_SELECT_FIELD_FK FOREIGN KEY (OUTPUT_FIELD_ID) REFERENCES DATASET_SCHEMA_FIELD(ID);

CREATE TABLE PIPELINE_STEP_WINDOW_PARTITION (
    PIPELINE_STEP_SELECT_ID BIGINT,
    FIELD_NAME VARCHAR(255),
    CONSTRAINT PIP_STEP_WIN_PART_FK FOREIGN KEY (PIPELINE_STEP_SELECT_ID) REFERENCES PIPELINE_STEP_SELECT(ID)
);

CREATE TABLE PIPELINE_STEP_WINDOW_ORDER (
    PIPELINE_STEP_SELECT_ID BIGINT,
    FIELD_NAME VARCHAR(255),
    DIRECTION VARCHAR(4),
    PRIORITY INTEGER,
    CONSTRAINT PIP_STEP_WIN_ORD_FK FOREIGN KEY (PIPELINE_STEP_SELECT_ID) REFERENCES PIPELINE_STEP_SELECT(ID)
);

CREATE TABLE PIPELINE_WINDOW_STEP (
  ID BIGINT NOT NULL PRIMARY KEY,
  SCHEMA_IN_ID BIGINT NOT NULL ,
  SCHEMA_OUT_ID BIGINT NOT NULL,
  CONSTRAINT WINDOW_STEP_FK FOREIGN KEY (ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT WINDOW_SCHEMA_IN_FK FOREIGN KEY (SCHEMA_IN_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT WINDOW_SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);
