ALTER TABLE DATASET ADD ROW_KEY_SEED BIGINT NULL;
ALTER TABLE DATASET ADD RUN_KEY BIGINT DEFAULT 1;
ALTER TABLE DATASET ADD LAST_UPDATED DATETIME2;

GO

UPDATE DATASET SET
ROW_KEY_SEED = CASE WHEN PIPELINE_JOB_ID IS NOT NULL THEN PIPELINE_JOB_ID ELSE STAGING_JOB_ID END,
RUN_KEY = ID,
LAST_UPDATED = CREATED_TIME
;

ALTER TABLE DATASET ADD CONSTRAINT UNIQUE_DATASET_RUN UNIQUE (NAME, ENTITY_CODE, REFERENCE_DATE, RUN_KEY);

ALTER TABLE STAGING_DATA_SET ADD DATASET_ID BIGINT DEFAULT NULL;

GO

UPDATE STAGING_DATA_SET
SET STAGING_DATA_SET.DATASET_ID = D.ID
FROM DATASET D
  INNER JOIN STAGING_DATA_SET
  ON D.STAGING_JOB_ID = STAGING_DATA_SET.SERVICE_REQUEST_ID AND D.NAME = STAGING_DATA_SET.DATASET
;
