ALTER TABLE SVC_SERVICE_REQUEST ADD START_TIME DATETIME2 DEFAULT NULL;
ALTER TABLE SVC_SERVICE_REQUEST ADD END_TIME DATETIME2 DEFAULT NULL;
ALTER TABLE SVC_SERVICE_REQUEST ADD STATUS VARCHAR(10);
ALTER TABLE SVC_SERVICE_REQUEST ADD EXIT_CODE VARCHAR(10);

GO

UPDATE SVC_SERVICE_REQUEST
SET
    START_TIME = BJE.START_TIME,
    END_TIME = BJE.END_TIME,
    STATUS = BJE.STATUS,
    EXIT_CODE = BJE.EXIT_CODE
FROM BATCH_JOB_EXECUTION BJE
WHERE SVC_SERVICE_REQUEST.JOB_EXECUTION_ID = BJE.JOB_EXECUTION_ID;