ALTER TABLE PIPELINE_STEP_INVC_DATASET ADD DATASET_RUN_KEY BIGINT NULL;

GO

UPDATE PIPELINE_STEP_INVC_DATASET
SET PIPELINE_STEP_INVC_DATASET.DATASET_RUN_KEY = D.RUN_KEY
FROM DATASET D
  INNER JOIN PIPELINE_STEP_INVC_DATASET
  ON D.ID = PIPELINE_STEP_INVC_DATASET.DATASET_ID
;