CREATE TABLE CAL_HOLIDAY (
  ID BIGINT NOT NULL PRIMARY KEY,
  PRODUCT_NAME VARCHAR(255) NOT NULL,
  HOLIDAY_DATE DATE NOT NULL,
  NAME VARCHAR(255),
    CONSTRAINT UNIQ_CALENDAR_PRODUCT UNIQUE (PRODUCT_NAME, HOLIDAY_DATE)
);
