ALTER TABLE PIPELINE_STEP_FILTER DROP CONSTRAINT PIP_STEP_FILTER_UNIQUE;

ALTER TABLE PIPELINE_STEP_FILTER ADD PIPELINE_STEP_ID_TEMP BIGINT not null default(0);
GO
UPDATE PIPELINE_STEP_FILTER SET PIPELINE_STEP_ID_TEMP = PIPELINE_STEP_ID;
ALTER TABLE PIPELINE_STEP_FILTER DROP CONSTRAINT  PIP_STEP_FILTER_FK;
ALTER TABLE PIPELINE_STEP_FILTER DROP COLUMN PIPELINE_STEP_ID;
GO

EXEC sp_rename '[PIPELINE_STEP_FILTER].[PIPELINE_STEP_ID_TEMP]', 'PIPELINE_STEP_ID', 'COLUMN';

ALTER TABLE PIPELINE_STEP_FILTER ADD CONSTRAINT PIP_STEP_FILTER_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP;

ALTER TABLE PIPELINE_STEP_FILTER ALTER COLUMN FILTER VARCHAR(MAX);