// Find All Schemas
GET {{context-path}}/api/internal/tables/
Authorization: Basic {{user-pass}}

###


// Find All Tables
GET {{context-path}}/api/internal/features
Authorization: Basic {{user-pass}}

###


// Find All Staged Datasets
GET {{context-path}}/api/v1/datasets?page=0  &size=3&sort=createdTime,desc
Authorization: Basic {{user-pass}}

###


// Find All Staged Datasets By Entity Code and Reference Date
GET {{context-path}}/api/v1/datasets
                           ?datasetName=dataset
                           &entityCode=code
                           &referenceDate=2000-01-01
                           &sort=createdTime,desc
                           &page=0  &size=10
Authorization: Basic {{user-pass}}

###


// Find All Staging Jobs
GET {{context-path}}/api/v1/jobs?sort=jobExecutionId,desc
Authorization: Basic {{user-pass}}

###


// Find All Configured Host Addresses and Ports
GET {{context-path}}/api/internal/services
Authorization: Basic {{user-pass}}

###


// Find All Dataset Source Files (csv)
GET {{context-path}}/api/internal/datasets/source/files
Authorization: Basic {{user-pass}}

###
// Find Dataset Rows
GET {{context-path}}/api/v1/drillback/datasets/-100?size=10&page=0
Authorization: Basic {{user-pass}}

###