// Remove Schema With ID
DELETE {{context-path}}/api/internal/tables/-10
Authorization: Basic {{user-pass}}

###


// Create FRY14QCIL Schema
POST {{context-path}}/api/v1/productConfigs/50000/schemas
Content-Type: application/json

< RELATED_ENTITIES.json


###
