ALTER TABLE PIPELINE_STEP_FILTER DROP CONSTRAINT PIP_STEP_FILTER_UNIQUE;

ALTER TABLE PIPELINE_STEP_FILTER ADD (PIPELINE_STEP_ID_TEMP DECIMAL(19) DEFAULT 0 not null);
UPDATE PIPELINE_STEP_FILTER SET PIPELINE_STEP_ID_TEMP = PIPELINE_STEP_ID;
ALTER TABLE PIPELINE_STEP_FILTER DROP COLUMN PIPELINE_STEP_ID;
ALTER TABLE PIPELINE_STEP_FILTER RENAME COLUMN PIPELINE_STEP_ID_TEMP TO PIPELINE_STEP_ID;
ALTER TABLE PIPELINE_STEP_FILTER ADD CONSTRAINT PIP_STEP_FILTER_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP;

ALTER TABLE PIPELINE_STEP_FILTER ADD (FILTER_CLOB CLOB);
UPDATE PIPELINE_STEP_FILTER SET FILTER_CLOB = FILTER;
ALTER TABLE PIPELINE_STEP_FILTER DROP COLUMN FILTER;
ALTER TABLE PIPELINE_STEP_FILTER RENAME COLUMN FILTER_CLOB TO FILTER;



