CREATE SEQUENCE "HIBERNATE_SEQUENCE" INCREMENT BY 1 START WITH 10000 CACHE 10000 NOCYCLE;

create table DATASET_SCHEMA
(
  ID NUMBER(19) not null
    primary key,
  NAME VARCHAR2(255)
    constraint DATASET_SCHEMA_UNIQUE
    unique,
  CREATED_BY VARCHAR2(50),
  CREATED_TIME TIMESTAMP(6),
  VERSION VARCHAR2(15),
  HAS_DATASETS NUMBER(1)
);

create table DATASET_SCHEMA_FIELD
(
  ID NUMBER(19) not null
    primary key,
  NAME VARCHAR2(255),
  FIELD_TYPE VARCHAR2(50),
  NULLABLE NUMBER(1),
  DATASET_SCHEMA_ID NUMBER(19) not null
    constraint DATASET_SCHEMA_FIELD_FK
    references DATASET_SCHEMA,
  DATE_FORMAT VARCHAR2(50),
  DEC_SCALE NUMBER,
  DEC_PRECISION NUMBER,
  MAX_LENGTH NUMBER,
  MIN_LENGTH NUMBER,
  REGULAR_EXPRESSION VARCHAR2(100),
  constraint DATASET_SCHEMA_FIELD_UNIQUE
  unique (DATASET_SCHEMA_ID, NAME)
);


create table SEC_USER
(
  ID NUMBER(19) not null
    primary key,
  USERNAME VARCHAR2(255)
    constraint UNIQUE_USERNAME_CONSTRAINT
    unique,
  PASSWORD VARCHAR2(255)
);

create table VALIDATION_RULE
(
  ID NUMBER not null
    primary key,
  RULE_ID VARCHAR2(100),
  RULE_TYPE VARCHAR2(50),
  SEVERITY VARCHAR2(50),
  VERSION NUMBER,
  START_DATE TIMESTAMP(6),
  END_DATE TIMESTAMP(6),
  NAME VARCHAR2(100),
  DESCRIPTION VARCHAR2(2000),
  EXPRESSION VARCHAR2(1000),
  DATASET_SCHEMA_ID NUMBER(19) not null
    constraint RULE_DATASET_SCHEMA_FK
    references DATASET_SCHEMA,
  constraint UNIQUE_RULE
  unique (DATASET_SCHEMA_ID, RULE_ID, VERSION, START_DATE, END_DATE)
);

create table PRODUCT_CONFIG
(
  ID NUMBER not null
    primary key,
  NAME VARCHAR2(200) not null
    constraint PRODUCT_CONFIG_NAME_UNIQUE
    unique,
  VERSION VARCHAR2(50) not null
);

create table PRODUCT_CONFIG_DATASET_SCHEMA
(
  PRODUCT_CONFIG_ID NUMBER not null
    constraint PCDS_PRODUCT_CONFIG_FK
    references PRODUCT_CONFIG,
  DATASET_SCHEMA_ID NUMBER not null
    constraint PCDS_DATASET_SCHEMA_FK
    references DATASET_SCHEMA,
  constraint PRODUCT_CONFIG_SCHEMA_UN
  unique (PRODUCT_CONFIG_ID, DATASET_SCHEMA_ID)
);

create table VALIDATION_RULE_SCHEMA_FIELD
(
  VALIDATION_RULE_ID NUMBER not null
    constraint VALIDATION_RULE_FK
    references VALIDATION_RULE,
  SCHEMA_FIELD_ID NUMBER not null
    constraint FIELD_FK
    references DATASET_SCHEMA_FIELD,
  constraint V_RULE_S_FIELD_PK
  primary key (VALIDATION_RULE_ID, SCHEMA_FIELD_ID)
);

create table VALIDATION_RULE_EXAMPLE
(
  ID NUMBER not null
    primary key,
  VALIDATION_RULE_ID NUMBER
    constraint V_RULE_EXAMPLE_TO_V_RULE_FK
    references VALIDATION_RULE,
  EXPECTED_RESULT VARCHAR2(5) not null
);

create table VALIDATION_RULE_EXAMPLE_FIELD
(
  ID NUMBER not null
    primary key,
  VALIDATION_RULE_EXAMPLE_ID NUMBER
    constraint V_R_EXMPL_FIELD_V_R_EXMPL_FK
    references VALIDATION_RULE_EXAMPLE,
  NAME VARCHAR2(255),
  VALUE VARCHAR2(500)
);
