ALTER TABLE DATASET_SCHEMA ADD MAJOR_VERSION NUMBER;
ALTER TABLE DATASET_SCHEMA ADD START_DATE DATE;
ALTER TABLE DATASET_SCHEMA ADD END_DATE DATE;
ALTER TABLE DATASET_SCHEMA ADD LATEST NUMBER(1) NOT NULL;

alter table DATASET_SCHEMA
  drop constraint DATASET_SCHEMA_UNIQUE;

alter table DATASET_SCHEMA ADD CONSTRAINT PHYS_NAME_UNIQUE UNIQUE (PHYSICAL_TABLE_NAME, MAJOR_VERSION);
alter table DATASET_SCHEMA ADD CONSTRAINT DISP_NAME_UNIQUE UNIQUE (DISPLAY_NAME, MAJOR_VERSION);

