
CREATE TABLE PIPELINE (
  ID NUMBER(19, 0) NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) DEFAULT NULL,
  PRODUCT_ID NUMBER(38, 0),
  CONSTRAINT PIPELINE_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_CONFIG (ID)
);

CREATE TABLE PIPELINE_STEP (
  ID NUMBER(19, 0) NOT NULL PRIMARY KEY,
  PIPELINE_ID NUMBER(19, 0) NOT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  DESCRIPTION VARCHAR(2500) DEFAULT NULL,
  TYPE VARCHAR(255) DEFAULT NULL,
  SCHEMA_IN_ID NUMBER(19, 0) NOT NULL ,
  SCHEMA_OUT_ID NUMBER(19, 0) NOT NULL,
  CONSTRAINT PIPELINE_FK FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE (ID),
  CONSTRAINT SCHEMA_IN_FK FOREIGN KEY (SCHEMA_IN_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);

CREATE TABLE PIPELINE_STEP_SELECT (
  PIPELINE_STEP_ID NUMBER(19, 0) NOT NULL,
  SELECTS VARCHAR(255) NOT NULL,
  CONSTRAINT PIP_STEP_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT UNIQUE_VALUE PRIMARY KEY (PIPELINE_STEP_ID, SELECTS)
)