ALTER TABLE DATASET_SCHEMA
ADD PRODUCT_ID NUMBER(38, 0);

UPDATE DATASET_SCHEMA DS1
SET PRODUCT_ID = (SELECT P.ID
                  FROM DATASET_SCHEMA DS2
                    join PRODUCT_CONFIG_DATASET_SCHEMA PDS on DS2.ID = PDS.DATASET_SCHEMA_ID
                    join PRODUCT_CONFIG P on P.ID = PDS.PRODUCT_CONFIG_ID
                  WHERE DS1.ID = DS2.ID);

ALTER TABLE DATASET_SCHEMA ADD CONSTRAINT DS_PRODUCT_FK
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_CONFIG (ID);

ALTER TABLE DATASET_SCHEMA
MODIFY PRODUCT_ID NUMBER(38, 0) NOT NULL;