ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN MESSAGE_ID;
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN SENDER_SYSTEM_ID;
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN RECEIVER_SERVICE_NAME;
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN CORRELATION_ID;
ALTER TABLE SVC_SERVICE_REQUEST DROP COLUMN IS_DELETED;

ALTER TABLE DATASET MODIFY NAME VARCHAR(100);
ALTER TABLE DATASET MODIFY TABLE_NAME VARCHAR(100);

ALTER TABLE STAGING_DATA_SET MODIFY DATASET VARCHAR(100);
ALTER TABLE STAGING_DATA_SET MODIFY TABLE_NAME VARCHAR(100);
