CREATE TABLE VALIDATION_RULE_SET (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME        VARCHAR(100) NOT NULL,
  DATASET_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE VALIDATION_RULE (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VALIDATION_RULE_SET_ID BIGINT NOT NULL,
  REGULATOR_ID VARCHAR(100),
  RULE_TYPE VARCHAR(50),
  SEVERITY VARCHAR(50),
  VERSION INTEGER,
  START_DATE DATETIME DEFAULT NULL,
  END_DATE DATETIME DEFAULT NULL,
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(2000),
  EXPRESSION VARCHAR(1000),
  CONSTRAINT RULE_RULE_SET_FK FOREIGN KEY (VALIDATION_RULE_SET_ID) REFERENCES VALIDATION_RULE_SET (ID)
);
