CREATE TABLE PRODUCT_CONFIG (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL,
  VERSION VARCHAR(50) NOT NULL,
  CONSTRAINT PRODUCT_CONFIG_NAME_UNIQUE UNIQUE (NAME)
);

CREATE TABLE PRODUCT_CONFIG_DATASET_SCHEMA (
  PRODUCT_CONFIG_ID BIGINT NOT NULL,
  DATASET_SCHEMA_ID BIGINT NOT NULL,
  CONSTRAINT PCDS_PRODUCT_CONFIG_FK FOREIGN KEY (PRODUCT_CONFIG_ID) REFERENCES PRODUCT_CONFIG (ID),
  CONSTRAINT PCDS_DATASET_SCHEMA_FK FOREIGN KEY (DATASET_SCHEMA_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT PRODUCT_CONFIG_SCHEMA_UN UNIQUE (PRODUCT_CONFIG_ID, DATASET_SCHEMA_ID)
);