ALTER TABLE VALIDATION_RULE
  ADD DATASET_SCHEMA_ID BIGINT,
  ADD CONSTRAINT RULE_DATASET_SCHEMA_FK FOREIGN KEY (DATASET_SCHEMA_ID) REFERENCES DATASET_SCHEMA (ID);

UPDATE VALIDATION_RULE R1
LEFT JOIN (
    SELECT R.ID, DS.ID AS DATASET_SCHEMA_ID FROM DATASET_SCHEMA DS
      INNER JOIN VALIDATION_RULE_SET RS ON DS.VALIDATION_RULE_SET_ID = RS.ID
      INNER JOIN VALIDATION_RULE R ON RS.ID = R.VALIDATION_RULE_SET_ID
  ) R2
ON R1.ID = R2.ID
SET R1.DATASET_SCHEMA_ID = R2.DATASET_SCHEMA_ID
;

ALTER TABLE VALIDATION_RULE
  MODIFY DATASET_SCHEMA_ID BIGINT NOT NULL,
  DROP FOREIGN KEY RULE_RULE_SET_FK,
  DROP INDEX UNIQUE_RULE,
  ADD CONSTRAINT UNIQUE_RULE UNIQUE (DATASET_SCHEMA_ID, RULE_ID, VERSION, START_DATE, END_DATE),
  DROP COLUMN VALIDATION_RULE_SET_ID;

ALTER TABLE DATASET_SCHEMA
  DROP FOREIGN KEY VALIDATION_RULE_SET_FK,
  DROP COLUMN VALIDATION_RULE_SET_ID;

DROP TABLE VALIDATION_RULE_SET;