ALTER TABLE PRODUCT_CONFIG
  ADD CREATED_TIME DATETIME,
ADD IMPORT_REQUEST_ID BIGINT,
DROP INDEX PRODUCT_CONFIG_NAME_UNIQUE,
ADD CONSTRAINT PRODUCT_CONFIG_UNIQUE unique (NAME, VERSION);

UPDATE PRODUCT_CONFIG
SET CREATED_TIME = '2018-10-01 00:00:00';

ALTER TABLE PRODUCT_CONFIG
  MODIFY CREATED_TIME DATETIME NOT NULL;