
CREATE TABLE PIPELINE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PIPELINE_STEP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  PIPELINE_ID BIGINT NOT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  DESCRIPTION VARCHAR(2500) DEFAULT NULL,
  TYPE VARCHAR(255) DEFAULT NULL,
  SCHEMA_IN_ID BIGINT NOT NULL ,
  SCHEMA_OUT_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PIPELINE_FK FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE (ID),
  CONSTRAINT SCHEMA_IN_FK FOREIGN KEY (SCHEMA_IN_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);

CREATE TABLE PIPELINE_STEP_SELECT (
  PIPELINE_STEP_ID BIGINT NOT NULL,
  SELECTS VARCHAR(255) DEFAULT '' NOT NULL ,
  CONSTRAINT PIP_STEP_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT UNIQUE_VALUE PRIMARY KEY (PIPELINE_STEP_ID, SELECTS)
)