

CREATE TABLE PIPELINE_MAP_STEP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SCHEMA_IN_ID BIGINT NOT NULL ,
  SCHEMA_OUT_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT MAP_STEP_FK FOREIGN KEY (ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT MAP_SCHEMA_IN_FK FOREIGN KEY (SCHEMA_IN_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT MAP_SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);

INSERT INTO PIPELINE_MAP_STEP (ID, SCHEMA_IN_ID, SCHEMA_OUT_ID)
 SELECT ID, SCHEMA_IN_ID, SCHEMA_OUT_ID FROM PIPELINE_STEP WHERE TYPE = 'MAP';

CREATE TABLE PIPELINE_AGGREGATION_STEP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SCHEMA_IN_ID BIGINT NOT NULL ,
  SCHEMA_OUT_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT AGG_STEP_FK FOREIGN KEY (ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT AGG_SCHEMA_IN_FK FOREIGN KEY (SCHEMA_IN_ID)  REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT AGG_SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);

INSERT INTO PIPELINE_AGGREGATION_STEP (ID, SCHEMA_IN_ID, SCHEMA_OUT_ID)
 SELECT ID, SCHEMA_IN_ID, SCHEMA_OUT_ID FROM PIPELINE_STEP WHERE TYPE = 'AGGREGATION';

ALTER TABLE PIPELINE_STEP DROP FOREIGN KEY SCHEMA_IN_FK;
ALTER TABLE PIPELINE_STEP DROP SCHEMA_IN_ID;
ALTER TABLE PIPELINE_STEP DROP FOREIGN KEY SCHEMA_OUT_FK;
ALTER TABLE PIPELINE_STEP DROP SCHEMA_OUT_ID;

CREATE TABLE PIPELINE_JOIN_STEP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SCHEMA_OUT_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT JOIN_STEP_FK FOREIGN KEY (ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT JOIN_SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);

CREATE TABLE PIPELINE_STEP_JOIN(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  PIPELINE_STEP_ID BIGINT NOT NULL,
  LEFT_SCHEMA_ID BIGINT NOT NULL,
  LEFT_JOIN_FIELD_ID BIGINT NOT NULL,
  RIGHT_SCHEMA_ID BIGINT NOT NULL,
  RIGHT_JOIN_FIELD_ID BIGINT NOT NULL,
  JOIN_TYPE VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PIP_STEP_JOIN_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT PIP_STEP_L_SCHEMA_FK FOREIGN KEY (LEFT_SCHEMA_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT PIP_STEP_L_FIELD_FK FOREIGN KEY (LEFT_JOIN_FIELD_ID) REFERENCES DATASET_SCHEMA_FIELD (ID),
  CONSTRAINT PIP_STEP_R_SCHEMA_FK FOREIGN KEY (RIGHT_SCHEMA_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT PIP_STEP_R_FIELD_FK FOREIGN KEY (RIGHT_JOIN_FIELD_ID) REFERENCES DATASET_SCHEMA_FIELD (ID)
);

CREATE TABLE PIPELINE_STEP_INVC_DATASET (
  PIPELINE_STEP_INVOCATION_ID BIGINT NOT NULL,
  DATASET_ID BIGINT NOT NULL,
  CONSTRAINT PIP_INVC_STEP_INVC_FK FOREIGN KEY (PIPELINE_STEP_INVOCATION_ID) REFERENCES PIPELINE_STEP_INVOCATION (ID),
  CONSTRAINT PIP_INVC_STEP_DATASET_FK FOREIGN KEY (DATASET_ID) REFERENCES DATASET (ID),
  CONSTRAINT PIP_INVC_STEP_DATASET_PK PRIMARY KEY (PIPELINE_STEP_INVOCATION_ID, DATASET_ID)
);

INSERT INTO PIPELINE_STEP_INVC_DATASET
  SELECT ID AS PIPELINE_STEP_INVOCATION_ID, INPUT_DATASET_ID AS DATASET_ID FROM PIPELINE_STEP_INVOCATION;

ALTER TABLE PIPELINE_STEP_INVOCATION DROP FOREIGN KEY PSI_IN_DATASET_FK;

ALTER TABLE PIPELINE_STEP_INVOCATION DROP INPUT_DATASET_ID;