CREATE TABLE CAL_HOLIDAY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  PRODUCT_NAME VARCHAR(255) NOT NULL,
  HOLIDAY_DATE DATE NOT NULL,
  NAME VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT UNIQ_CALENDAR_PRODUCT UNIQUE (PRODUCT_NAME, HOLIDAY_DATE)
);
