ALTER TABLE DATASET ADD ROW_KEY_SEED BIGINT(20) DEFAULT NULL;
ALTER TABLE DATASET ADD RUN_KEY BIGINT(20) DEFAULT 1;
ALTER TABLE DATASET ADD LAST_UPDATED DATETIME;

UPDATE DATASET SET
ROW_KEY_SEED = CASE WHEN PIPELINE_JOB_ID IS NOT NULL THEN PIPELINE_JOB_ID ELSE STAGING_JOB_ID END,
RUN_KEY = ID,
LAST_UPDATED = CREATED_TIME
;

ALTER TABLE DATASET ADD CONSTRAINT UNIQUE_DATASET_RUN UNIQUE (NAME, ENTITY_CODE, REFERENCE_DATE, RUN_KEY);

ALTER TABLE STAGING_DATA_SET ADD DATASET_ID BIGINT(20) DEFAULT NULL;

UPDATE STAGING_DATA_SET SDS
INNER JOIN (
    SELECT D.ID AS DATASET_ID, D.NAME AS DATASET_NAME
    FROM DATASET D
) D
ON D.DATASET_ID = SDS.SERVICE_REQUEST_ID AND D.DATASET_NAME = SDS.DATASET
SET SDS.DATASET_ID = D.DATASET_ID
;
