ALTER TABLE PIPELINE_STEP_INVC_DATASET ADD DATASET_RUN_KEY BIGINT(20) DEFAULT NULL;

UPDATE PIPELINE_STEP_INVC_DATASET PSID
INNER JOIN (
    SELECT D.ID AS DATASET_ID, D.RUN_KEY AS DATASET_RUN_KEY
    FROM DATASET D
) D
ON D.DATASET_ID = PSID.DATASET_ID
SET PSID.DATASET_RUN_KEY = D.DATASET_RUN_KEY
WHERE PSID.DATASET_ID IS NOT NULL
;