ALTER TABLE PIPELINE_STEP_SELECT
    DROP FOREIGN KEY PIP_STEP_FK,
    DROP PRIMARY KEY,
    ADD ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ADD OUTPUT_FIELD_ID BIGINT,
    ADD IS_WINDOW BIT DEFAULT 0;

ALTER TABLE PIPELINE_STEP_SELECT
    ADD CONSTRAINT PIP_STEP_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP (ID),
    ADD CONSTRAINT PIP_STEP_SELECT_FIELD_FK FOREIGN KEY (OUTPUT_FIELD_ID) REFERENCES DATASET_SCHEMA_FIELD(ID);

CREATE TABLE PIPELINE_STEP_WINDOW_PARTITION (
    PIPELINE_STEP_SELECT_ID BIGINT,
    FIELD_NAME VARCHAR(255),
    CONSTRAINT PIP_STEP_WIN_PART_FK FOREIGN KEY (PIPELINE_STEP_SELECT_ID) REFERENCES PIPELINE_STEP_SELECT(ID)
);

CREATE TABLE PIPELINE_STEP_WINDOW_ORDER (
    PIPELINE_STEP_SELECT_ID BIGINT,
    FIELD_NAME VARCHAR(255),
    DIRECTION VARCHAR(4),
    PRIORITY INTEGER,
    CONSTRAINT PIP_STEP_WIN_ORD_FK FOREIGN KEY (PIPELINE_STEP_SELECT_ID) REFERENCES PIPELINE_STEP_SELECT(ID)
);

CREATE TABLE PIPELINE_WINDOW_STEP (
  ID BIGINT NOT NULL PRIMARY KEY,
  SCHEMA_IN_ID BIGINT NOT NULL ,
  SCHEMA_OUT_ID BIGINT NOT NULL,
  CONSTRAINT WINDOW_STEP_FK FOREIGN KEY (ID) REFERENCES PIPELINE_STEP (ID),
  CONSTRAINT WINDOW_SCHEMA_IN_FK FOREIGN KEY (SCHEMA_IN_ID) REFERENCES DATASET_SCHEMA (ID),
  CONSTRAINT WINDOW_SCHEMA_OUT_FK FOREIGN KEY (SCHEMA_OUT_ID) REFERENCES DATASET_SCHEMA (ID)
);
