ALTER TABLE PIPELINE_STEP_FILTER ADD (PIPELINE_STEP_ID_TEMP BIGINT not null DEFAULT 0);

UPDATE PIPELINE_STEP_FILTER SET PIPELINE_STEP_ID_TEMP = PIPELINE_STEP_ID;

ALTER TABLE PIPELINE_STEP_FILTER DROP FOREIGN KEY PIP_STEP_FILTER_FK;
ALTER TABLE PIPELINE_STEP_FILTER DROP COLUMN PIPELINE_STEP_ID;
ALTER TABLE PIPELINE_STEP_FILTER CHANGE COLUMN PIPELINE_STEP_ID_TEMP PIPELINE_STEP_ID BIGINT not null;
ALTER TABLE PIPELINE_STEP_FILTER ADD CONSTRAINT PIP_STEP_FILTER_FK FOREIGN KEY (PIPELINE_STEP_ID) REFERENCES PIPELINE_STEP (ID);

ALTER TABLE PIPELINE_STEP_FILTER ADD (FILTER_TEMP LONGTEXT not null);
UPDATE PIPELINE_STEP_FILTER SET FILTER_TEMP = FILTER;
ALTER TABLE PIPELINE_STEP_FILTER DROP COLUMN FILTER;
ALTER TABLE PIPELINE_STEP_FILTER CHANGE COLUMN FILTER_TEMP FILTER LONGTEXT not null;
