ALTER TABLE PIPELINE_STEP_SELECT ADD (SELECTS_TEMP LONGTEXT not null);
UPDATE PIPELINE_STEP_SELECT SET SELECTS_TEMP = SELECTS;
ALTER TABLE PIPELINE_STEP_SELECT DROP COLUMN SELECTS;
ALTER TABLE PIPELINE_STEP_SELECT CHANGE COLUMN SELECTS_TEMP SELECTS LONGTEXT not null;
